#! /bin/sh

### BEGIN INIT INFO
# Provides:		proxies
# Required-Start:	$all
# Required-Stop:	$all
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description: smart proxy server, support UDP/DOT/TCP
### END INIT INFO
stop_st_proxy(){
  if [ -f "/var/run/proxies.pid" ]; then
    pid=$(cat /var/run/proxies.pid)
    if [ "$pid" != "" ]; then
      kill -9 $(cat /var/run/proxies.pid)
    fi
  fi
  return 0
}
start_st_proxy(){
  rm -rf proxies.*
  nohup /usr/local/bin/proxies>/tmp/proxies.log 2>/tmp/proxies.error &
  return 0
}
case "$1" in
  start)
        start_st_proxy
        ;;
  stop)
        stop_st_proxy
        ;;
  restart)
        stop_st_proxy
        start_st_proxy
        ;;
  *)
        echo "Usage: proxies <start|stop|restart>"
esac

exit 0